# 1. The Frontend (lets-make-it.hu)
server {
    listen 80;
    server_name localhost; # Locally we use localhost, but this represents the main domain
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
# 2. The API (api.localhost)
server {
    listen 8080; # We use a different port locally to simulate a different domain
    server_name localhost;
    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }
}